#include <ncurses.h>

#define CWHITE COLOR_PAIR(1)
#define CYELLOW COLOR_PAIR(2)
#define CBLUE COLOR_PAIR(3)
#define CBLACK COLOR_PAIR(4)

const uint64_t patterns[][8][8] = {
    {
        // Humber logo, index 0
        CBLUE,   CBLUE,   CBLUE,   CBLUE,   CBLUE,   CBLUE,   CBLUE,   CBLUE,
        CBLUE,   CBLUE,   CWHITE,  CBLUE,   CBLUE,   CWHITE,  CBLUE,   CYELLOW,
        CBLUE,   CBLUE,   CWHITE,  CBLUE,   CBLUE,   CWHITE,  CYELLOW, CYELLOW,
        CBLUE,   CBLUE,   CWHITE,  CBLUE,   CBLUE,   CWHITE,  CYELLOW, CYELLOW,
        CBLUE,   CBLUE,   CWHITE,  CWHITE,  CWHITE,  CWHITE,  CYELLOW, CYELLOW,
        CBLUE,   CBLUE,   CWHITE,  CYELLOW, CYELLOW, CWHITE,  CYELLOW, CYELLOW,
        CBLUE,   CYELLOW, CWHITE,  CYELLOW, CYELLOW, CWHITE,  CYELLOW, CYELLOW,
        CYELLOW, CYELLOW, CYELLOW, CYELLOW, CYELLOW, CYELLOW, CYELLOW, CYELLOW,
    },

    {
        // White square, index 1
        CWHITE, CWHITE, CWHITE, CWHITE, CWHITE, CWHITE, CWHITE, CWHITE,
        CWHITE, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CWHITE,
        CWHITE, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CWHITE,
        CWHITE, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CWHITE,
        CWHITE, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CWHITE,
        CWHITE, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CWHITE,
        CWHITE, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CBLACK, CWHITE,
        CWHITE, CWHITE, CWHITE, CWHITE, CWHITE, CWHITE, CWHITE, CWHITE,
    },
};

void cursDisplayPattern(int yOffset, int xOffset, const uint64_t pattern[8][8]);
void cursUpdateLevel(int yOffset, int xOffset, float xa, float ya);